server:
  port: 8080
  servlet:
    context-path: /UniCharity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UniversityCharityDB
    username: root
    password: tiendat07022003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.web: DEBUG

jwt:
  signerKey: "K1YJD9Mt3V3wklqFpuYQXZhKSMdh6UZyLBb/nvXKBk1Lw3yXtRYTcpLqwOa8ACsc"



